load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "rel_lib",
    srcs = [
      "//rel-lib/src:rel_lib_src"
    ],
    hdrs = [
      "//rel-lib/src:rel_lib_hdr"
    ],
    includes = ["src/"],
    visibility = ["//visibility:public"],
)
