filegroup(
    name = "rel_lib_src",
    srcs = glob([
        "*.cpp",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rel_lib_hdr",
    srcs = glob([
        "*.h",
    ]),
    visibility = ["//visibility:public"],
)

